### ISSUE TITLE
Failed to open repository on Google Cloud

### ISSUE THREAD

**Issue by Aare07** [emuell/restic-browser#100]
First, thank you for your effort and your work.
Im not anble to connect to an repository on the Google Cloud.
What i did:
Setup an Bucket and run restic to backup -> works
Created with the SDK an Access Token -> in my opinion successful.
When i try to open the repository with the Google token and the repository Password there comes:
_Failed to open repository: Fatal: parsing repository location failsed: gs:invalid format: bucket name or path not found_
See the full error message and URI in attachement
<img width="603" alt="restic-browser-google-cloud-error" src="https://github.com/emuell/restic-browser/assets/69456851/823a2710-f797-4189-9a13-53c018ddc8a0">
My Bucket name is: gs://backup-hr-pc-giga2020

- have i overlooked something?
- when i look at the browser, it looks like there is a space between gs: and // in the URI
- or are the - in the name or the name lenght an problem?

And on the way: 
Is there an wiki, forum or aditional doku? 
As the Google Token creation is for windows users not that straightforward i would document this step by step, if appreciated.

Thanks for any help.
Greetings Aare

**Comment by Aare07** [comment]
I can access the bucket with restic to write and read. Here i use the authentication with JSON credentials file.
This option in restic browser would be easy to me: download JSON from Google serviceaccount, stick restic browser to the file or use the ENV from restic.  (in another issue you have asked which authentication you schould chose, for me, the JSON credentials file is the easiest and works perfect with restic)

I tried the different writings of the bucket repository, unfortunately no one worked...

My ENV with working restic access in Powershell:
$Env:GOOGLE_PROJECT_ID="backup-hr"
$Env:GOOGLE_APPLICATION_CREDENTIALS="C:\xyz\restic\backup-hr-xyz.json"
$Env:RESTIC_REPOSITORY="gs:backup-hr-pc-giga2020:/pc-giga2020"
$Env:RESTIC_PASSWORD_FILE="C:\xyz\restic\restic.pw.txt"

To get the token for the defined Google Cloud serviceaccount of the bucket:
I installend the SDK https://cloud.google.com/sdk/docs/install   
Overall i used this howto https://saturncloud.io/blog/how-to-get-an-access-token-from-google-cloud/

As im not an programmer, i can not test the the Google Cloud bucket acces with the token.
At this point, i think my "token thing" is not correct.
But to test this, i need help, as the access-tests i found are done in programming languages or Linux....
Greetings

**Comment by Aare07** [comment]
Thank you.
One thing to mention: my restic has only acces to the bucket via an serviceuser, no rights to te project itself (for restic init the "storage backup admin" and later on for backup, ls and restore the "storage backup user" rights). 
The idea: encript trojans with cloud / restic knowledge can only access the bucket, not the  project. The bucket itself is protected by: Protection = Soft delete policy = 30 days)

Im glad to test the new version as an end user, dummy user :)

**Comment by Aare07** [comment]
Thank you so much
Works perfect 👍

**Comment by Aare07** [comment]
Fixed with the new Google Clout Auth.
Works with these settings:
<img width="466" alt="restic-browser-google-cloud-settings" src="https://github.com/emuell/restic-browser/assets/69456851/fd5bb84d-fe63-428c-b626-3ab8c8b0927c">

**Comment by emuell** [comment]
Thanks for checking!
