### ISSUE TITLE
Dependency error when running on Fedora 40

### ISSUE THREAD

**Issue by jameskhedley** [emuell/restic-browser#111]
Just downloaded the linux release and tried to run it, but it didn't run and I got this error:

```$ ./restic-browser 
./restic-browser: symbol lookup error: /lib64/libwebkit2gtk-4.0.so.37: undefined symbol: gst_video_info_dma_drm_from_caps
```

I have got webkit2gtk4.0 installed, also 4.1 - could that be the problem?

```$ rpm -qva | grep webkit2gtk
webkit2gtk4.0-2.44.1-2.fc40.x86_64
webkit2gtk4.0-devel-2.44.1-2.fc40.x86_64
webkit2gtk4.1-2.44.2-2.fc40.x86_64
webkit2gtk4.1-devel-2.44.2-2.fc40.x86_64
```

**Comment by emuell** [comment]
That's a symbol from gstreamer

https://gstreamer.freedesktop.org/documentation/video/video-info-dma-drm.html?gi-language=c#gst_video_info_dma_drm_from_caps

It's available in gstreamer >= 1.24

Which version is installed on your system?

**Comment by jameskhedley** [comment]
1.22 apparently

Presumably this works out of the box on Ubuntu, just not other repos?

**Comment by emuell** [comment]
Yes, that seems to work in other distros and likely will be an issue in webkit or [tauri](https://github.com/tauri-apps/tauri)? Could not find a similar issue in the tauri repo though.

**Comment by emuell** [comment]
@jameskhedley If you are still interested in running restic browser, please test if the new Linux AppImage works for you:
https://github.com/emuell/restic-browser/actions/runs/10558920486?pr=119
