### ISSUE TITLE
restic-browser does not start on Linux Mint 22 (Ubuntu 24.04)

### ISSUE THREAD

**Issue by brokfeld** [emuell/restic-browser#114]
./restic-browser: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory

**Comment by brokfeld** [comment]
See also issue #111

**Comment by parona-source** [comment]
https://github.com/tauri-apps/tauri/issues/9662

**Comment by emuell** [comment]
I'll try to build an appimage for the Linux release. As this includes all dependent shared libs this should work more reliably on most Linux distd out there...

**Comment by emuell** [comment]
@brokfeld here's an appimage or the restic browser app:
https://github.com/emuell/restic-browser/actions/runs/10558920486?pr=119

Please note that you need to `chmod +x` it before running it.
