### ISSUE TITLE
Can't open a repository, without a password

### ISSUE THREAD

**Issue by vmlemon** [emuell/restic-browser#122]
I decided to try "restic-browser" 0.3.1, for the first time, under Windows, just now. It appears that since my repository was created with the ```---insecure-no-password``` flag, "restic-browser" bails out, with the following error:

<img width="602" alt="image" src="https://github.com/user-attachments/assets/83a12acb-c825-4199-afd0-aaa97fe5e1ce">

When no password is entered, in the "Repository Password" field, of the "Open Repository" dialogue, and the "Repository Password" dialogue,  "restic-browser" should probably try to invoke Restic with ```---insecure-no-password```.

**Comment by jmclaren7** [comment]
Could you check the latest test build before @emuell takes a look, just in case it's fixed or behaves differently:

https://github.com/emuell/restic-browser/actions/runs/11091586376

**Comment by emuell** [comment]
I've now added support for empty passwords via the `---insecure-no-password` option here:
https://github.com/emuell/restic-browser/pull/124

Please note that this requires a restic version >= 0.17 to be installed. Previous restic versions did not allow empty passwords.

@vmlemon could you please check if the builds from the PR work for you?
https://github.com/emuell/restic-browser/actions/runs/11195521181?pr=124

I'll then merge this...

**Comment by vmlemon** [comment]
> I've now added support for empty passwords via the `---insecure-no-password` option here: #124
> 
> Please note that this requires a restic version >= 0.17 to be installed. Previous restic versions did not allow empty passwords.
> 
> @vmlemon could you please check if the builds from the PR work for you? https://github.com/emuell/restic-browser/actions/runs/11195521181?pr=124
> 
> I'll then merge this...

Sorry for the delayed response - I've had some personal things to contend with, so I've only just had chance to look at this.

Thanks for pointing to the automatic builds. It appears that it gets a little further, but doesn't identify development builds as being "equal to, or newer than 0.17":

![image](https://github.com/user-attachments/assets/9ba5f94b-58d3-412d-ba5f-d483432e9461)

On the flip-side, I've just noticed that they released Restic 0.17.1, just a few days ago, which *does* seem to work, with this release, with a passwordless repository:

![image](https://github.com/user-attachments/assets/9d359a5d-3875-4ac8-81de-a1f7d1ceed58)

**Comment by emuell** [comment]
> It appears that it gets a little further, but doesn't identify development builds as being "equal to, or newer than 0.17"

Test, that's technically correct, as the dev releases are a pre-release of a final release. A 0.17.0 *final* version would have worked too, so I think it's fine as it is.

Thanks for checking! Are there any other problems, or is it working for you now? Then I'll merge this...

**Comment by vmlemon** [comment]
Thanks! All worked as it should.
