### ISSUE TITLE
[UX] Show "container" instead of Bucket

### ISSUE THREAD

**Issue by Gill-Bates** [emuell/restic-browser#132]
When selecting an Azure Blob Storage, the UI should change to `container` instead of `bucket`.

![image](https://github.com/user-attachments/assets/444cd9af-b89f-45ee-8a36-18b3cb300c32)

**Comment by emuell** [comment]
Makes sence. Cleared up a few other labels [here](https://github.com/emuell/restic-browser/pull/133) as well.
