### ISSUE TITLE
Ubuntu 20.04 LTS GLIBC_2.34 GLIBC_2.32 not found

### ISSUE THREAD

**Issue by damoclark** [emuell/restic-browser#14]
Hi @emuell 

This looks like an exciting project.  Thanks for sharing your work.  

Just reporting that when I try to run Restic-Browser on Ubuntu 20.04.4 (amd64), I get the error:

```bash
$ ./Restic-Browser
./Restic-Browser: /lib/x86_64-linux/gnu/libc.so.6: version 'GLIBC_2.34' not found (required by ./Restic-Browser)
./Restic-Browser: /lib/x86_64-linux/gnu/libc.so.6: version 'GLIBC_2.32' not found (required by ./Restic-Browser)
```

The version of `libc.so.6` on my install is symlinked to `libc-2.31.so`.  😞 

I suspect this will be related to wails2, so not sure how you might overcome this one.  But 20.04 is a very common install base, and is supported by Canonical for another 3 years.

Damo.

**Comment by emuell** [comment]
> But 20.04 is a very common install base, and is supported by Canonical for another 3 years.

Yes, indeed. I tried to run it on Ubuntu 18, but wails2 did not work there: it compiled fine, but only an empty window was displayed. I then tried it on Ubuntu 22 and actually never tested on Ubuntu 20.

Does Wails2, or more specifically the Restic-Browser work for you, when you compile it from source as described here?
https://github.com/emuell/restic-browser#development

We could then update the github build matrix to use Ubuntu-20.04 for the prebuilt binaries.

**Comment by emuell** [comment]
Quickly tried building on Ubuntu 20.04 in the github action build-matrix:  does the binary below work for you? 

[Linux.tar.gz](https://github.com/emuell/restic-browser/files/9212104/Linux.tar.gz)

**Comment by damoclark** [comment]
Hey thanks for giving me a test build.  I don't have a build chain set up for Go.  It works!  I did get the following messages in the terminal window where I started it.  I'm using MATE as my desktop environment.  

But the application window displays and I can click on Open Repository button.

```
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal

(Restic-Browser:425841): Gdk-CRITICAL **: 13:43:44.680: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed
SetMinMaxSize - min: (0,0) max: (3008,1692)

(Restic-Browser:425841): Gdk-CRITICAL **: 13:43:44.680: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed
SetMinMaxSize - min: (0,0) max: (3008,1692)
SetSize:  1024 768
Center: 992x462
```

**Comment by emuell** [comment]
Thanks for checking. The next version will then be built on Ubuntu 20.04.

These warnings are from Wails. I believe a fix is already being worked on:
https://github.com/wailsapp/wails/issues/1653
