### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by damoclark** [emuell/restic-browser#16]
Something else to consider is for restic-browser to cache results when you explore the backup directory tree structure to view files.  At the moment, if you return to directories you have visited already (even going back up to parent directory), the reload of the files is just as slow as the first.  The delay is not trivial - at least for me and I'm working with a restic repo that is on a local disk.  

It might need to be an option to enable or not, as some users may not want to cache the file listings and directory structure on disk where they are using your tool, for security/privacy reasons.  They would have to endure the lag when navigating to different directories.  

I do love that switching between snapshots keeps the directory view on the same directory.  This is great when you need to restore a file from a particular directory, but not sure which snapshot to pull it from.  Very nice!  This is something that [backintime](https://github.com/bit-team/backintime) does.  It is a great GUI backup/restore tool to take some inspiration from.

Damo.

**Comment by emuell** [comment]
That's a great idea. When caching the contents in memory, I think we don't even need an option to disable the cache, as no sensitive data is written to disk. I'll give this a try in the next days. 

Also wasn't aware of https://github.com/bit-team/backintime. It looks really nice and is indeed something to get some inspiration from, as it serves a similar purpose.
