### ISSUE TITLE
"failed to restore file: unknown shorthand flag 'a' in -a"

### ISSUE THREAD

**Issue by benklaasen** [emuell/restic-browser#22]
Hi! Thank you for putting together this terrific tool. It's easy to install, and robust browsing a large restic archive. I'm running Restic-Browser-v0.2.2-beta-linux, on a restic archive on Backblaze B2.

I've browsed to a directory  five levels deep, backed up three years ago, and now I'm attempting to either 'view' (eye icon) or 'download' (down to disk icon) a file in that folder.

On clicking either of those icons, a red toast pops up, with the text  "Failed to restore file: unknown shorthand flag 'a' in -a". 

On attempting to download a file, a zero-byte file with the name of the desired file is created locally.

Is there a flag I can start the binary with, to enable logging?

**Comment by emuell** [comment]
Hi! 

Your installed restic version does not support the "-a" flag for the dump operation - this is a fairly new option it seems. I'm not sure when exactly it was added, but upgrading to the latest restic version should definitely fix this.

Ideally, we should check the installed restic version and print out a more useful error. Alternatively, I guess we could simply skip passing the -a option for older versions of restic?

**Comment by emuell** [comment]
Just checked: https://github.com/restic/restic/releases/tag/v0.12.0 is the first version of restic with the -a option.

**Comment by benklaasen** [comment]
Oh, fantastic, thank you. I'll upgrade and get back to you. This occurred on a laptop running the latest Zorin OS, a Ubuntu derivative.

**Comment by benklaasen** [comment]
Oh, this is nice!

```
beep@media:~$ sudo apt install restic
Reading package lists... Done
...
Preparing to unpack .../restic_0.9.6+ds-2_amd64.deb ...
Unpacking restic (0.9.6+ds-2) ...
Setting up restic (0.9.6+ds-2) ...
Processing triggers for man-db (2.9.1-1) ...
beep@media:~$ sudo restic self-update
writing restic to /usr/bin/restic
find latest release of restic at GitHub
latest version is 0.13.1
download SHA256SUMS
download SHA256SUMS.asc
GPG signature verification succeeded
download restic_0.13.1_linux_amd64.bz2
downloaded restic_0.13.1_linux_amd64.bz2
saved 18472960 bytes in /usr/bin/restic
successfully updated restic to version 0.13.1
```

**Comment by benklaasen** [comment]
Superb, just verified that an out-of-date `restic` binary was the issue. I updated it as above, restarted 0.2.2, and was able to browse to and download (or view) any arbitrary file several levels deep in an archive of arbitrary age.

I'll close this issue. Thank you for the guidance!
