### ISSUE TITLE
Add commandline support

### ISSUE THREAD

**Issue by KamikazeePL** [emuell/restic-browser#34]
Could add command line support?
To start restic-browser with repository address, password from batch file.

**Comment by emuell** [comment]
Right now it will pick up existing restic env variables and use them as initial config: 
Try setting `RESTIC_REPOSITORY` and `RESTIC_PASSWORD`, then start restic from than env. 
AWS_ACCESS_KEY_ID, B2_ACCOUNT_ID are also supported.

This probably is a bit unexpected for a GUI app, so allowing to explicitly setting/passing them may not hurt.

**Comment by JsBergbau** [comment]
@emuell 
It seems like restic-browser does not support some of the environment variables 
```
set RESTIC_REPOSITORY_FILE=resticRepository
```
When setting them backup works flawlessly, but restic-browser tells no repository selected. The password is already filled, so `set RESTIC_PASSWORD_FILE=resticPW` seems to work. When then entering the repository manually there is an error
`Failed to open repository: Fatal: Options -r and --repository-file are mutually exclusive, please specify only one`

**Comment by emuell** [comment]
Support for RESTIC_REPOSITORY_FILE has been added here:
https://github.com/emuell/restic-browser/commit/906f68705bb058f80da166bf81c2156895f4be04

But it's not released yet. You could try using the gitlab builds from here until it is:
 https://github.com/emuell/restic-browser/actions

**Comment by emuell** [comment]
... and a bunch of other args have been added here: https://github.com/emuell/restic-browser/pull/81
