### ISSUE TITLE
[Request] Allow To Save/Store Repo Credentials

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [emuell/restic-browser#40]
I'm not sure if this has been brought up before, but I'd love to not have to input my repo details every time I wanna view snapshots= contents.

Would there be a way to cache/save/store this info anywhere, and just have the repo kind of saved onto the client? If that's out of scope, then perhaps read from a file for all inputs, not just password?

I personally use Backblaze, so it's a lot of copy pasting every time.

Thanks!

Edit: Ideally you'd allow credentials to be saved for all types of repositories (local, S3, Backblaze), and allow for multiple repos to be saved too.

**Comment by emuell** [comment]
> Ideally you'd allow credentials to be saved for all types of repositories (local, S3, Backblaze), and allow for multiple repos to be saved too.

Yes, that indeed would be nice, although we then would need to save the passwords too, which is always needs to be done with extra care. 

There are a few other feature requests open, which require saving some form of a preference state for the Restic browser. Right now it uses no persistent options at all.  I'll try to add this first and then see how we can memorize previously used repository locations. 

---

A workaround for now, which I'm using, is starting the Restic Browser from a shell with predefined restic repo environment variables:

If you e.g. define the RESTIC_REPOSITORY, RESTIC_PASSWORD in a shell and then start the Restic Browser from there, it will pick them up and use them as the initial repository credentials.

**Comment by JohnAtl** [comment]
Thanks for creating Restic Browser!

Just tried setting those environment variables, and Restic Browser didn't act on them.
Might I suggest using the _FILE versions as well? This would allow secrets to stay in a file. E.g. ~/.config/restic.passwd, then define the env var RESTIC_PASSWORD_FILE=~/.config/restic.passwd.

**Comment by emuell** [comment]
Hi. This should work, even with RESTIC_PASSWORD_FILE. What platform are you on? Are you setting the ENV values globally?

Try setting the env values in a terminal, then run restic browser directly from that terminal.

**Comment by emuell** [comment]
See https://github.com/emuell/restic-browser/issues/61 for further discussion of this topic.
