### ISSUE TITLE
Failed to open B2 repo: failed to parse snapshot info: invalid character 'b' after top-level value

### ISSUE THREAD

**Issue by frdmn** [emuell/restic-browser#41]
Just tired to open my Backblaze B2 restic repo, but the following error message is shown in the GUI:

```
Failed to open repository. failed to parse snapshot info: invalid character 'b' after top-level value
```

<img width="925" alt="Bildschirm­foto 2023-01-18 um 09 06 52" src="https://user-images.githubusercontent.com/944459/213117904-df15e454-4c48-4c5b-b76c-cb66faf6b23c.png">

My repo is located at `/minecraft` so I've put `b2:<bucketname>:/minecraft` for the the bucket settings. Am I doing anything wrong here?

**Comment by emuell** [comment]
Have you probably added an extra `b2: ` prefix to the repository path? That's not needed, after selecting the repository type "backblaze b2" in the Restic Browser "Open Repository" dialog.

**Comment by frdmn** [comment]
Thanks for the quick reply. No I haven't specifically added the `b2:` in the settings:

<img width="400" alt="Bildschirm­foto 2023-01-18 um 10 55 58" src="https://user-images.githubusercontent.com/944459/213140700-92e945f5-fd8a-4d7e-9373-0e970c55e81e.png">

**Comment by emuell** [comment]
That's definitely an unusual bucket name. The ":/" characters are not valid value for a b2 repository path. But the error message does not match.

Does it work with the restic command line tool?

**Comment by frdmn** [comment]
The `obi-wan-restic` is the bucket name - `/minecraft` is path within the bucket that the repository is using. Yes, it does work on the CLI (with `b2:obi-wan-restic:/minecraft` as full bucket name)

**Comment by frdmn** [comment]
Here'a s few more screenshots from the "Browse bucket files" option from Backblaze UI to depict the file system within the bucket:

<img width="710" alt="Bildschirm­foto 2023-01-18 um 16 42 40" src="https://user-images.githubusercontent.com/944459/213217496-a05ccb78-8235-4c4c-b810-957bb109984f.png">

<img width="736" alt="Bildschirm­foto 2023-01-18 um 16 42 48" src="https://user-images.githubusercontent.com/944459/213217487-24399f9b-4365-4c86-b74f-f2cef59f509c.png">

As you can see I have two restic repositories within one single B2 bucket (`/minecraft` and `/vaultwarden`).

**Comment by emuell** [comment]
Sorry for the late reply. I've just checked if the subfolders in the backblaze repository are the problem, but this seems to work fine here after some testing. 

But for some reason your repositories snapshot list seems to contain unexpected data.

Could you please run the following in a command in a terminal and send me a snippet of the resulting output? You can send it over privately to me or mask parts of it if it contains any personal data.

`restic -r b2:b2:obi-wan-restic:/minecraft snapshots --json`

The expected output is something like this:
```
[{"time":"2023-01-28T11:43:19.6633988+01:00","tree":"079aa5f92d06ecadf00d7a8def5dbc644b090dff2cba6b5cbcb2e5e8e236c8b1","paths":["C:\\Users\\emuell\\bla"],"hostname":"DESKTOP-T1GPS4B","username":"DESKTOP-PC\\emuell","id":"874ee3b79c5bc315b0b28afc3c8509ab5a17ef244e1da55d4a2c194a7b54921d","short_id":"874ee3b7"}]
```

Also, is the result huge? Maybe that' the problem then.

Which version of restic are you using?

**Comment by frdmn** [comment]
No problem! Here's the output:

```
$ restic -r b2:obi-wan-restic:/minecraft snapshots --json
[{"time":"2023-01-13T11:24:00.797779629Z","tree":"a6260d2df66bf59bc1c58bc4571d7cbc9f62cf8c48959198810ca8600988eadd","paths":["/data"],"hostname":"37fc97876458","username":"root","excludes":["*.jar","cache","logs"],"tags":["mc_backups","world"],"id":"4e193cce2923be3f835e16823c675f91dfa76dd9cd43753d2f2eb3720b59ad7b","short_id":"4e193cce"},{"time":"2023-01-13T11:37:17.190967156Z","tree":"7f1b6ceb08b4838d45abe44f949839e194a0fef6d957f4a512f188b8a0c848b1","paths":["/data"],"hostname":"690f4a80395e","username":"root","excludes":["*.jar","cache","logs"],"tags":["mc_backups","world"],"id":"4d067f8d242883b93ec0c27542dcd1bb7463193423648f4cd68b739b17ad995f","short_id":"4d067f8d"},{"time":"2023-01-15T16:40:01.058447921Z","parent":"beb8fb01760d9aa8216ac5afa6d6494283857187ac29ae74fc483510d49b64b6","tree":"01f90b98f71f48ecd8ffbd49830f404b7f9f5e575c1c3ce146b1de4a6e79e2c6","paths":["/data"],"hostname":"32f2994284ff","username":"root","excludes":["*.jar","cache","logs"],"tags":["mc_backups","world"],"id":"7bad2bed5eb13c8742bf6de10739cc1b5da8a9ffa96ecb2b6ed6bf0604e5d818","short_id":"7bad2bed"},{"time":"2023-01-22T13:35:33.360501614Z","parent":"4155d95302d967b23482ed5a01e84842b4e6576b470aa67bac9fb581225ac604","tree":"c057f34c146de695d67f7ad52a3bf9069a86d3827e5b18481a428e01a2877793","paths":["/data"],"hostname":"32f2994284ff","username":"root","excludes":["*.jar","cache","logs"],"tags":["mc_backups","world"],"id":"d027e358944d4b02d669c3d9803cfc870b9fac04dae57cead9cfad4c74bcdeb0","short_id":"d027e358"},{"time":"2023-01-24T13:37:51.755498593Z","parent":"6321a3c0937f8c7eeff7f25612ed356a458ebff028e2732625537fed40ce6fcc","tree":"57ad057c96274380f60396e6bba32ace780c41b91d69dbe4280a436e131b056b","paths":["/data"],"hostname":"32f2994284ff","username":"root","excludes":["*.jar","cache","logs"],"tags":["mc_backups","world"],"id":"c2a0876e7a00e8b3b5359d2132a6ef822625bb92dd50f8e37fc9d48a1869214e","short_id":"c2a0876e"},{"time":"2023-01-25T13:38:58.649220288Z","parent":"c2a0876e7a00e8b3b5359d2132a6ef822625bb92dd50f8e37fc9d48a1869214e","tree":"26262fae0588d72f1f8b9f050588df0a2cd042a0f05333747cbaabca0c927cee","paths":["/data"],"hostname":"32f2994284ff","username":"root","excludes":["*.jar","cache","logs"],"tags":["mc_backups","world"],"id":"ec049984150ca3b835516ebcd34f51ae75899db72eb9e910038d6e8238dd5ca1","short_id":"ec049984"},{"time":"2023-01-26T13:40:06.906364458Z","parent":"ec049984150ca3b835516ebcd34f51ae75899db72eb9e910038d6e8238dd5ca1","tree":"e8290b5b1d0c0035198f0f20f347772044917c9c64dbd89847d50a3e2170cd0c","paths":["/data"],"hostname":"32f2994284ff","username":"root","excludes":["*.jar","cache","logs"],"tags":["mc_backups","world"],"id":"d7abeeff7e8a1c42f411001ac8e6de871a98ed1f282b104ecc38edff9954eab4","short_id":"d7abeeff"},{"time":"2023-01-27T13:40:32.578932485Z","parent":"d7abeeff7e8a1c42f411001ac8e6de871a98ed1f282b104ecc38edff9954eab4","tree":"ca4cfc8726736bd2010449348fdd366e57145436c0a05b966a86909d10f4391e","paths":["/data"],"hostname":"32f2994284ff","username":"root","excludes":["*.jar","cache","logs"],"tags":["mc_backups","world"],"id":"ec5eda39d1e16a0d4756067d278efda1b46fa3b74b1937aebcd2eb7561416c9b","short_id":"ec5eda39"}]
b2_download_file_by_name: 404: : b2.b2err
```

I'm using the latest version from Homebrew on macOS (13.2):

```
~ ❯ restic version
restic 0.15.0 compiled with go1.19.5 on darwin/arm64
```

**Comment by frdmn** [comment]
Could it be the non-JSON line in the output at the very end?

```
b2_download_file_by_name: 404: : b2.b2err
```

Would match the error original message, complaining about the invalid character 'b'.

**Comment by emuell** [comment]
Thanks. That's very helpful.

> Could it be the non-JSON line in the output at the very end?

Yes, very likely. I'll check if we somehow can ignore such errors.

**Comment by emuell** [comment]
Just wanted to add a hackaround for this, but it seems this now also got fixed in restic itself: see https://github.com/restic/restic/issues/4144

**Comment by emuell** [comment]
I've now also hacked around this in https://github.com/emuell/restic-browser/pull/45
So please use the latest Restic Browser unreleased build from https://github.com/emuell/restic-browser/actions/runs/4097276395 or download the latest version of restic to get that fixed on your side...

**Comment by frdmn** [comment]
@emuell Just upgraded to restic 0.15.1 which seem to resolve the issue for me \o/.

Many thanks!
