### ISSUE TITLE
Command Line arguments?

### ISSUE THREAD

**Issue by grahamIT** [emuell/restic-browser#42]
Is it possible to preconfigure restic-browser to open a backup repo via a command line argument? I would be nice to be able to create a shortcut that opens the application and prompts the user for a password.

**Comment by emuell** [comment]
Hi. There's no command line support right now, but Restic Browser already picks up relevant restic ENV values. See https://github.com/emuell/restic-browser/issues/34#issuecomment-1304855874 for details. 

If we'd allow command line args, there actually would be a lot of them to configure AWS, B2 and RClone repositories, such as AWS_ACCESS_KEY_ID, B2_ACCOUNT_ID, AZURE_ACCOUNT_NAME...
