### ISSUE TITLE
MacOS - Apple Silicon Build

### ISSUE THREAD

**Issue by dia3olik** [emuell/restic-browser#46]
Hey @emuell !
Thanks a lot for this project!
I suggest to build the next release as an Universal Binary or at least to add a binary compiled for Apple Silicon.
Thanks again!!

**Comment by emuell** [comment]
Good point. I've added them now and will include them in the next release.

You can download some preview builds here, in case you want to test them now:
https://github.com/emuell/restic-browser/actions/runs/4150719473
