### ISSUE TITLE
On ARM Mac - program cant open

### ISSUE THREAD

**Issue by Fischmuetze** [emuell/restic-browser#49]
Runs on Montery without any glitches, but on ARM CPU " program cant open". I wonder why this happens since normally Rosetta2 should able to handle that. Any suggestions.This isn't a security issue.

**Comment by Fischmuetze** [comment]
download again and extract solved the issue ... no idea what's wrong

**Comment by emuell** [comment]
Ooops. Indeed. The executable flag was missing on the binary on OSX. 
`chmod +x restic-browser.app/Contents/MacOS/restic-browser`

Just have fixed that, and uploaded a new macOS version at https://github.com/emuell/restic-browser/releases/tag/v0.2.6

You could also try the new Tauri based releases at https://github.com/emuell/restic-browser/actions which have better support for macOS: https://github.com/emuell/restic-browser/issues/35#issuecomment-1783850417
