### ISSUE TITLE
[Improvement] cmd argument for path to restic.exe

### ISSUE THREAD

**Issue by Cyberklabauter** [emuell/restic-browser#50]
It would be great, if  the restic-browser would look for restic.exe in its own base directory before opening the dialog to chose restic.exe manually. 

Beside that, I would like to have an commandline option to start restic-browser with the path to the restic.exe like "restic-browser.exe -r.restic c:\mypersonalresticfolder\restic.exe".

**Comment by AxelPetermann** [comment]
I would also like to have that feature.
