### ISSUE TITLE
Does restic browser cache contents?

### ISSUE THREAD

**Issue by parasiteoflife** [emuell/restic-browser#51]
Ok, I have to first lay out my set up.

- I use Windows.
- I backup entire drives.
- Because of point 2 all snapshots root directories are a single directory named a single char -the drive partition letter- (ie. `\N\` or `\E\`).
- I backup using rclone to the cloud.

I'm asking this because it takes a really long time to load a snapshot only to load the root folder, in this example lets say the directory `N`, and then when I double click that folder `N` it takes another long time to load again the contents, then if I enter another directory another wait, and in the status bar it says "Fetching Files" so all in all it seems it is not caching anything, I thought it exported the whole snapshot content to json, parsed it and then showed it, is this a bug? It's been happening forever

**Comment by emuell** [comment]
> Oh, I think I get it, it caches previously retrieved information, it doesn't retrieve the data of the whole snapshot and the parses it so I guess I should make a feature request, please confirm.

Yes, exactly. Restic-Browser only caches already fetched snapshot content. For newly fetched content, we rely on restic to cache snapshot content list requests, but I don't think it really caches anything here. This basically means that the `restic ls SNAPSHOT_ID /` takes quite a long time to complete in your case.

I agree that this is annoying, especially for repositories in the cloud, but I don't really see how we can fix this as long as we use the restic binary for all operations.
