### ISSUE TITLE
Support other s3 compatible servers.

### ISSUE THREAD

**Issue by tbellembois** [emuell/restic-browser#52]
It would be great to be able to use other amazon s3 compatible providers such as OpenStack instances.
Adding a field to specify the server URL should be enough to provide this functionality.

**Comment by emuell** [comment]
Shouldn't adding the URL as part of the bucket name already work?

e.g.
Bucket (s3: )
https://some_domain:1234/my_repository

Unfortunately, I don't currently have access to an OpenStack or MiniIO instance to test this here.

**Comment by tbellembois** [comment]
Yes it works !
But just with `some_domain:1234/my_repository`.
