### ISSUE TITLE
Restic Browser does not use the RESTIC_REPOSITORY_FILE environment variable

### ISSUE THREAD

**Issue by JohnAtl** [emuell/restic-browser#54]
In my testing, RESTIC_REPOSITORY works fine, but RESTIC_REPOSITORY_FILE is ignored.
RESTIC_PASSWORD_FILE seems to work fine too.

**Comment by emuell** [comment]
This indeed isn't supported right now, but will be supported soon via:  https://github.com/emuell/restic-browser/pull/55
