### ISSUE TITLE
Cannot connect to remote Rclone repository over SSH

### ISSUE THREAD

**Issue by colans** [emuell/restic-browser#56]
I'm not able to access a repository running via Rclone on a remote server over SSH.  If I select the RCLONE method, and enter the "rclone:remote-storage:bucket_name" for the Bucket, I get:

> Failed to open repository: Fatal: unable to open repo at rclone:remote-storage:bucket_name: cmd.Start: exec: "rclone": executable file not found in $PATH

Normally I run it like this:

* `/usr/bin/restic --option rclone.program="ssh username@example.com rclone" --option rclone.args="serve restic --stdio --b2-hard-delete --drive-use-trash=false --verbose" --repo rclone:remote-storage:bucket_name --password-file /etc/restic/password --verbose ${@}
`

Maybe there's no allowance for starting the REST server over SSH and running Rclone through the tunnel?  Is this the problem?

The Restic documentation for this is at [Other Services via rclone](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone).

**Comment by mtissington** [comment]
I am seeing the same error but this is the command I use which works from terminal on macos

`restic -r rclone:onedrive:..... snapshots'

**Comment by emuell** [comment]
There's an unpublished fix for the rclone PATH handling here: https://github.com/emuell/restic-browser/pull/92
You can download binaries containing this fix here: https://github.com/emuell/restic-browser/actions/runs/7425075508

The fix will lookup rclone in some "common" paths and also adds a command line arg to specify the path to rclone manually. 
 The rclone.args option is not supported, but can probably be set via rclone's regular environment settings. However, you will need to run Restic Browser from the terminal then to set the environment variables.

**Comment by mtissington** [comment]
Working - thanks.

**Comment by caos-linux** [comment]
> I'm not able to access a repository running via Rclone on a remote server over SSH. If I select the RCLONE method, and enter the "rclone:remote-storage:bucket_name" for the Bucket, I get:
> 
> > Failed to open repository: Fatal: unable to open repo at rclone:remote-storage:bucket_name: cmd.Start: exec: "rclone": executable file not found in $PATH
> 
> Normally I run it like this:
> 
>     * `/usr/bin/restic --option rclone.program="ssh username@example.com rclone" --option rclone.args="serve restic --stdio --b2-hard-delete --drive-use-trash=false --verbose" --repo rclone:remote-storage:bucket_name --password-file /etc/restic/password --verbose ${@} `
> 
> 
> Maybe there's no allowance for starting the REST server over SSH and running Rclone through the tunnel? Is this the problem?
> 
> The Restic documentation for this is at [Other Services via rclone](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone).

I was in a similar situation. I solved with this workaround:
```
restic-browser --repo rclone:remote-storage:bucket_name --password-file /etc/restic/password \
--restic /absolute_path/restic.sh
```
where `restic.sh is`
```
#!/bin/bash
/usr/bin/restic --option rclone.program="ssh username@example.com rclone" \
--option rclone.args="serve restic --stdio --b2-hard-delete --drive-use-trash=false --verbose" $@
```
