### ISSUE TITLE
Unable to supply certificate or disable certificate checks

### ISSUE THREAD

**Issue by ProactiveServices** [emuell/restic-browser#57]
restic-browser is currently unable to open repos on REST servers using a self-signed certificate. A method that would pass to restic a certificate and/or the `--insecure-tls` option would be helpful.

**Comment by JsBergbau** [comment]
Can you try using `set RESTIC_CACERT=mykey` like
Using the environment variable it should work. Don't know which OS you are on. I can support you more with Linux and Windows if you want further assistance.

**Comment by emuell** [comment]
Added a new insecure TLS option for remote locations here: https://github.com/emuell/restic-browser/pull/81

This feature is not yet release, but can be tested with the latest binaries from: https://github.com/emuell/restic-browser/actions/runs/6575514068
