### ISSUE TITLE
wamp interference, port 80

### ISSUE THREAD

**Issue by gaby64** [emuell/restic-browser#70]
I do web development with wamp always running, could you use an alternative port for your app?
Restic-Browser loads up localhost on the frontend and does not work when I have wamp services running.

**Comment by metal12345** [comment]
Similar issue here. I use port 1443 and the restic-browser program shows a different service that I host

**Comment by emuell** [comment]
This was probably a bug in older versions of Wails. Could you please check if the latest Restic browser builds from the master work for you?

https://github.com/emuell/restic-browser/actions

The latest (but not yet released) restic-browser builds use Wails 2.41. The latest build uses Wails 2.3.1.

**Comment by FeroxFolf** [comment]
I had the same issue but using the latest build seems to have fixed it for me, thanks :)

**Comment by emuell** [comment]
This is now finally released: https://github.com/emuell/restic-browser/releases/tag/v0.26
