### ISSUE TITLE
Dump operation of 'NAME ARCHIVE failed: unknown shorthand flag: 'a'in -a

### ISSUE THREAD

**Issue by 12elotro** [emuell/restic-browser#74]
When I try to view an archive or extract it into a zip always the same error Dump operation of 'NAME ARCHIVE failed: unknown shorthand flag: 'a'in -a

If I extract it it just works.

I use Linux Mint 20.3 Cinnamon.

**Comment by emuell** [comment]
Which version of restic do you have installed? Have you tried upgrading it?

**Comment by 12elotro** [comment]
> Which version of restic do you have installed? Have you tried upgrading it?
I have updated restic and it already works. Thanks greetings

**Comment by 12elotro** [comment]
I have updated restic and it already works. Thanks greetings
