### ISSUE TITLE
Some passwords with special characters do not work

### ISSUE THREAD

**Issue by kapitainsky** [emuell/restic-browser#97]
I could not connect to my repo until I changed its password to one without any special characters.

I am not sure which character causes issues as some other passwords with special characters work. 

Here you are example of the password which does not work with restic browser.

```
a7zL4rpf3%xpmh%vsw4zw$c6oT#LfUo308uOtfxu@
```

It works perfectly fine with restic command line though.

**Comment by emuell** [comment]
Thanks for the example.

Is it on MacOS, Linux or Windows?
How was the password set? Via the location dialogue in the Restic Browser or was it set as an ENV variable before starting the Restic Browser?

**Comment by kapitainsky** [comment]
macOS - Sonoma 14.3.1

**Comment by emuell** [comment]
I've just tested this on MacOS and Windows, but I can't reproduce the problem with the password you mentioned above.
Are you sure there are no typos in the password, or spaces at the beginning or end of the password while you tried it?

**Comment by jmclaren7** [comment]
Hi guys, I was also unable to reproduce it on MacOS with the example password, I did however have an auto capitalization issue when I pasted or typed, not sure how I did it though, whenever the password was typed correctly it worked perfectly. I tried it for both the repository password and the password for connecting to an s3 compatible bucket.

**Comment by kapitainsky** [comment]
> I've just tested this on MacOS and Windows, but I can't reproduce the problem with the password you mentioned above.
> Are you sure there are no typos in the password, or spaces at the beginning or end of the password while you tried it?

Thank you for trying.

Hmmm... Let's say I am not new to computers...  I have tried many times thinking about all stupid mistakes I could make.

But facts are facts. I will try to reproduce it again and will report back.

**Comment by kapitainsky** [comment]
Ok another password I can reproduce it. I use local repository:

```
$ export RESTIC_REPOSITORY="/Volumes/DBSamsung-SSD-500-Temp/restic-test"
$ export RESTIC_PASSWORD="xT7zL4rpf3%xpmb%vsD2zw$L6oE#LfUo308kROtfDu@"

$ echo $RESTIC_PASSWORD
xT7zL4rpf3%xpmb%vsD2zw#LfUo308kROtfDu@

$ restic init
created restic repository c8d138ade0 at /Volumes/DBSamsung-SSD-500-Temp/restic-test

$ restic backup .
repository c8d138ad opened (version 2, compression level auto)
created new cache in /Users/kptsky/Library/Caches/restic
no parent snapshot found, will read all files

Files:           4 new,     0 changed,     0 unmodified
Dirs:            1 new,     0 changed,     0 unmodified
Added to the repository: 480.350 KiB (35.663 KiB stored)

processed 4 files, 478.102 KiB in 0:00
snapshot 6586c5d8 saved

$ restic snapshots
repository c8d138ad opened (version 2, compression level auto)
ID        Time                 Host        Tags        Paths
----------------------------------------------------------------------------------------
6586c5d8  2024-03-02 07:28:07  DB-laptop               /Users/kptsky/Temp/test
----------------------------------------------------------------------------------------
1 snapshots
```

Now I can NOT open this repository using restic-browser but when I change password (`restic key passwd`) to something different it works.

**Comment by jmclaren7** [comment]
I was able to reproduce it on macOS and not Windows and I narrowed the problem character down to "$". So it seems like it's specifically local repositories on macOS.

I tried the following password which also caused the issue.
`export RESTIC_PASSWORD="aa$bb"`

The example password without the $ did not cause the issue.
`export RESTIC_PASSWORD="xT7zL4rpf3%xpmb%vsD2zwXL6oE#LfUo308kROtfDu@"`

**Comment by kapitainsky** [comment]
> I was able to reproduce it on macOS and not Windows and I narrowed the problem character down to "$". So it seems like it's specifically local repositories on macOS.
> 
> I tried the following password which also caused the issue. `export RESTIC_PASSWORD="aa$bb"`
> 
> The example password without the $ did not cause the issue. `export RESTIC_PASSWORD="xT7zL4rpf3%xpmb%vsD2zwXL6oE#LfUo308kROtfDu@"`

The question is whether it is restic-browser problem or restic and local environment. I am not sure.

**Comment by jmclaren7** [comment]
@emuell will have a better idea but my guess is that it's nothing to do with restic or the environment (outside of being macOS or maybe file system type).

One thing you could test in the meantime is this older version: https://github.com/emuell/restic-browser/releases/tag/v0.2.6

**Comment by emuell** [comment]
Thanks for nailing this. I still can't replicate this here on MacOS Ventura 13.6.4, but will investigate further.

**Comment by kapitainsky** [comment]
The answer was in my previous post - but I noticed it only now:

```
$  export RESTIC_PASSWORD="xT7zL4rpf3%xpmb%vsD2zw$L6oE#LfUo308kROtfDu@"

$ echo $RESTIC_PASSWORD
xT7zL4rpf3%xpmb%vsD2zw#LfUo308kROtfDu@
```

There is no issue with rclone browser....

Here even more clear:

```
$ export RESTIC_PASSWORD="pa$$word"
$ echo $RESTIC_PASSWORD
pa4911word
```

Looks like `$` needs escaping.

```
$ export RESTIC_PASSWORD="pa\$\$word"

$ echo $RESTIC_PASSWORD
pa$$word
```

**Comment by kapitainsky** [comment]
Thank you guys for your time. The issue was as often between chair and keyboard. But some lesson has been learnt here.

For anybody with similar "problem" - in bash when exporting password use single quotes.

```
$ export RESTIC_PASSWORD='pa$$word'

$ echo $RESTIC_PASSWORD
pa$$word
```
