### ISSUE TITLE
How to pass restic command line options (e.g. sftp.args)

### ISSUE THREAD

**Issue by causalmask** [emuell/restic-browser#99]
Is there a way to pass restic command line options when opening a repository?  I specifically need to pass `-o "sftp.args=-i /path/to/private_key"` when accessing an sftp repo.

**Comment by emuell** [comment]
That's currently not possible, but maybe you could connect via rclone then instead?

**Comment by causalmask** [comment]
Thanks for the suggestion.

I had been passing those sftp.args to restic before I started using restic-browser, but I just realized I could also add the appropriate ssh config values to the ~/.ssh/config (inside the container I'm running) and that would work the same.
